name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost  # для сервиса postgres
      DB_PORT: 5432
    
    services:
      postgresql_main:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Проверяем наличие изменений
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Линтинг
        run: flake8 ./articles/ --exclude=articles/admin.py,articles/migrations/,articles/models.py

      - name: Тестирование
        run: python manage.py test
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}